modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPLv3"
[[mods]]
modId="simpleplanes"
version="${file.jarVersion}"
displayName="Simple Planes"
authors="adoxentor, Przemyk"
description='''
Adds upgradeable planes and helicopters.
'''
[[dependencies.simpleplanes]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleplanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
