modLoader="javafml"
loaderVersion="[39,)"
license="GNU LGPLv3"
[[mods]]
modId="simpleplanes"
version="${file.jarVersion}"
displayName="Simple Planes"
authors="adoxentor, Przemyk"
description='''
Adds upgradeable planes and helicopters.
'''
[[dependencies.simpleplanes]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleplanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
