modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"
[[mods]]
modId="simpleplanes"
version="${file.jarVersion}"
displayName="Simple Planes"
authors="adoxentor, Przemyk"
description='''
Adds upgradeable planes and helicopters.
'''
[[dependencies.simpleplanes]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleplanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
