modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="GNU LGPLv3"
[[mods]]
modId="simpleplanes"
version="${file.jarVersion}"
displayName="Simple Planes"
authors="adoxentor, Przemyk"
description='''
Adds upgradeable planes and helicopters.
'''
[[dependencies.simpleplanes]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleplanes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
